include("multimeter/types.jl")
include("oscilloscope/types.jl")
include("power_supply/types.jl")
include("waveform_generator/types.jl")
include("MicroController/types.jl")
include("Rasberry_Pi/types.jl")