include("impedance_analyzer/types.jl")
include("multimeter/types.jl")
include("oscilloscope/types.jl")
include("power_supply/types.jl")
include("waveform_generator/types.jl")
#include("micro_controller/types.jl")
#include("rasberry_pi/types.jl")
